
/********************************************************************
*
*	文件	：	AT24C64MemData.h

*	管脚	：	

*	功能	：	数据存储
*
******************************************************************************/
#ifndef __AT24C64MemData_H
#define __AT24C64MemData_H
#include "main.h"

#define VALUE_CHECKDATA					0X05

/*	0X00-0X0F作为控制字节存储空间	*/
#define ADDR_CHECKDATA					0X00										//校验

/*	0X10--0XYY作为用户数据存储空间	*/
#define ADDR_BFLIP						0X10
#define ADDR_BVC						0X11
#define ADDR_MODE_V						0X12
#define ADDR_MODE_C						0X13

#define ADDR_V_PARAM_BASE				0X14
#define ADDR_V_SINGLE_FUNIT_START		ADDR_V_PARAM_BASE
#define ADDR_V_SINGLE_PULSENAD_START	(ADDR_V_SINGLE_FUNIT_START 		+ 1)
#define ADDR_V_SINGLE_AMPLNAD_START		(ADDR_V_SINGLE_PULSENAD_START	+ 1)
#define ADDR_V_SINGLE_PULSE_START		(ADDR_V_SINGLE_AMPLNAD_START	+ 1)		//高位在前，低位在后
#define ADDR_V_SINGLE_AMPL_START		(ADDR_V_SINGLE_PULSE_START		+ 8)

#define	ADDR_V_FREERUN_FUNIT_START		(ADDR_V_SINGLE_AMPL_START		+ 8)
#define ADDR_V_FREERUN_PULSENAD_START	(ADDR_V_FREERUN_FUNIT_START		+ 1)
#define ADDR_V_FREERUN_AMPLNAD_START	(ADDR_V_FREERUN_PULSENAD_START	+ 1)
#define ADDR_V_FREERUN_FREQNAD_START	(ADDR_V_FREERUN_AMPLNAD_START	+ 1)
#define ADDR_V_FREERUN_PULSE_START		(ADDR_V_FREERUN_FREQNAD_START	+ 1)
#define ADDR_V_FREERUN_AMPL_START		(ADDR_V_FREERUN_PULSE_START		+ 8)
#define ADDR_V_FREERUN_FREQ_START		(ADDR_V_FREERUN_AMPL_START		+ 8)

#define ADDR_V_TRAIN_FUNIT_START		(ADDR_V_FREERUN_FREQ_START		+ 8)
#define ADDR_V_TRAIN_PULSENAD_START		(ADDR_V_TRAIN_FUNIT_START		+ 1)
#define ADDR_V_TRAIN_AMPLNAD_START		(ADDR_V_TRAIN_PULSENAD_START	+ 1)
#define ADDR_V_TRAIN_FREQNAD_START		(ADDR_V_TRAIN_AMPLNAD_START		+ 1)
#define ADDR_V_TRAIN_DURATIONNAD_START	(ADDR_V_TRAIN_FREQNAD_START		+ 1)
#define ADDR_V_TRAIN_PULSE_START		(ADDR_V_TRAIN_DURATIONNAD_START + 1)
#define ADDR_V_TRAIN_AMPL_START			(ADDR_V_TRAIN_PULSE_START		+ 8)
#define ADDR_V_TRAIN_FREQ_START			(ADDR_V_TRAIN_AMPL_START		+ 8)
#define ADDR_V_TRAIN_DURATION_START		(ADDR_V_TRAIN_FREQ_START		+ 8)

#define ADDR_V_EXTBNC_FUNIT_START		(ADDR_V_TRAIN_DURATION_START	+ 8)
#define ADDR_V_EXTBNC_AMPLNAD_START		(ADDR_V_EXTBNC_FUNIT_START		+ 1)
#define ADDR_V_EXTBNC_AMPL_START		(ADDR_V_EXTBNC_AMPLNAD_START	+ 1)


#define ADDR_C_SINGLE_FUNIT_START		(ADDR_V_EXTBNC_AMPL_START		+ 8)
#define ADDR_C_SINGLE_PULSENAD_START	(ADDR_C_SINGLE_FUNIT_START		+ 1)
#define ADDR_C_SINGLE_AMPLNAD_START		(ADDR_C_SINGLE_PULSENAD_START	+ 1)
#define ADDR_C_SINGLE_PULSE_START		(ADDR_C_SINGLE_AMPLNAD_START	+ 1)
#define ADDR_C_SINGLE_AMPL_START		(ADDR_C_SINGLE_PULSE_START		+ 8)

#define ADDR_C_FREERUN_FUNIT_START		(ADDR_C_SINGLE_AMPL_START		+ 8)
#define ADDR_C_FREERUN_PULSENAD_START	(ADDR_C_FREERUN_FUNIT_START		+ 1)
#define ADDR_C_FREERUN_AMPLNAD_START	(ADDR_C_FREERUN_PULSENAD_START	+ 1)
#define ADDR_C_FREERUN_FREQNAD_START	(ADDR_C_FREERUN_AMPLNAD_START	+ 1)
#define ADDR_C_FREERUN_PULSE_START		(ADDR_C_FREERUN_FREQNAD_START	+ 1)
#define ADDR_C_FREERUN_AMPL_START		(ADDR_C_FREERUN_PULSE_START		+ 8)
#define ADDR_C_FREERUN_FREQ_START		(ADDR_C_FREERUN_AMPL_START		+ 8)

#define ADDR_C_TRAIN_FUNIT_START		(ADDR_C_FREERUN_FREQ_START		+ 8)
#define ADDR_C_TRAIN_PULSENAD_START		(ADDR_C_TRAIN_FUNIT_START		+ 1)
#define ADDR_C_TRAIN_AMPLNAD_START		(ADDR_C_TRAIN_PULSENAD_START	+ 1)
#define ADDR_C_TRAIN_FREQNAD_START		(ADDR_C_TRAIN_AMPLNAD_START		+ 1)
#define ADDR_C_TRAIN_DURATIONNAD_START	(ADDR_C_TRAIN_FREQNAD_START		+ 1)
#define ADDR_C_TRAIN_PULSE_START		(ADDR_C_TRAIN_DURATIONNAD_START + 1)
#define ADDR_C_TRAIN_AMPL_START			(ADDR_C_TRAIN_PULSE_START		+ 8)
#define ADDR_C_TRAIN_FREQ_START			(ADDR_C_TRAIN_AMPL_START		+ 8)
#define ADDR_C_TRAIN_DURATION_START		(ADDR_C_TRAIN_FREQ_START		+ 8)

#define ADDR_C_EXTBNC_FUNIT_START		(ADDR_C_TRAIN_DURATION_START	+ 8)
#define ADDR_C_EXTBNC_AMPLNAD_START		(ADDR_C_EXTBNC_FUNIT_START		+ 1)
#define ADDR_C_EXTBNC_AMPL_START		(ADDR_C_EXTBNC_AMPLNAD_START	+ 1)

#define MEMORYUPDATE_UPCNT_CLEAR		0
#define MEMORYUPDATE_UPCNT_START		1

void Memory_ConfigLoad(void);
void Memory_Poll(void);

#endif
